### ISSUE TITLE
Jump to line and column when opening vim

### ISSUE THREAD

**Issue by m-ghaoui** [mattn/vscode-openvim#1]
You should jump to the line and column the cursor is on when opening vim.

Similar to what happens here:

http://vim.wikia.com/wiki/Integrate_gvim_with_Visual_Studio

Add the command +"call cursor($(CurLine),$(CurCol))" to the execution.

Otherwise, great plugin!

**Comment by mattn** [comment]
fair enough. will do

**Comment by m-ghaoui** [comment]
Excellent! :-)
